spring.application.name=Medan Heritage Trails
server.port=8080
spring.thymeleaf.cache=false

# H2 Database configurations
spring.datasource.url=jdbc:h2:file:./data/jejakdeli;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# Google OAuth2 Configurations
google.client.id=1033994354890-mockclientid.apps.googleusercontent.com

# Mail configurations (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=example.user@gmail.com
spring.mail.password=exampleAppPassword123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

